### ISSUE TITLE
check translation string

### ISSUE THREAD

**Issue by Crash--** [cozy/create-cozy-app#1297]
We will add a check between fr/en/whatever.json files to see if we have difference between files (https://github.com/cozy/create-cozy-app/issues/1296), but we also need to parse the all app to extract string and check if the string is in the main translation file in order to avoid to use untranslated string (context https://github.com/cozy/cozy-drive/pull/1940/commits/025dcf04df5ab73f386384267dea87512f37aa54 string used but not defined)

**Comment by ptbrowne** [comment]
Closing since I put the link to a feature from banks that does that in #1296.
