### ISSUE TITLE
Do not override manifest keys if they already exist

### ISSUE THREAD

**Issue by ptbrowne** [cozy/create-cozy-app#1302]
If no manifest key is present in src/locales/{fr,en}.json, we should
not end up with empty locales in the manifest.webapp.

https://mattermost.cozycloud.cc/cozycloud/pl/bibmah3uridu3fbj979u1ef5aw

https://github.com/cozy/create-cozy-app/blob/master/packages/cozy-scripts/config/webpack.config.manifest.js#L38

**Comment by Crash--** [comment]
see https://github.com/cozy/create-cozy-app/blob/master/packages/cozy-scripts/config/webpack.config.manifest.js#L38-L44

**Comment by ptbrowne** [comment]
Fixed in https://github.com/cozy/create-cozy-app/pull/1303
