### ISSUE TITLE
Create cozy app doesn't start

### ISSUE THREAD

**Issue by nicolaspernoud** [cozy/create-cozy-app#1351]
Hello,

After creating an app with the `yarn create cozy-app mycozyapp` script from a nodejs 10 environnement, I got the following error messages when starting the app with `yarn start` command.

```
WARNING in ./node_modules/cozy-ui/transpiled/react/Portal/index.js
Module not found: Error: Can't resolve 'preact-portal' in '/app/mycozyapp/node_modules/cozy-ui/transpiled/react/Portal'
 @ ./node_modules/cozy-ui/transpiled/react/Portal/index.js
 @ ./node_modules/cozy-ui/transpiled/react/Modal/index.js
 @ ./node_modules/cozy-ui/transpiled/react/QuotaAlert/index.js
 @ ./node_modules/cozy-client/dist/hooks/useClientErrors.js
 @ ./node_modules/cozy-client/dist/hooks/index.js
 @ ./node_modules/cozy-client/dist/index.js
 @ ./src/targets/browser/index.jsx
 @ multi webpack-dev-server/client?http://localhost:8888/ webpack/hot/dev-server ./node_modules/@babel/polyfill/lib/index.js ./node_modules/cozy-scripts/utils/reactExposer.js ./src/targets/browser/index.jsx

ERROR in ./node_modules/string.prototype.trim/implementation.js
Module not found: Error: Can't resolve 'es-abstract/2020/RequireObjectCoercible' in '/app/mycozyapp/node_modules/string.prototype.trim'
 @ ./node_modules/string.prototype.trim/implementation.js 3:29-79
 @ ./node_modules/string.prototype.trim/index.js
 @ ./node_modules/node-polyglot/index.js
 @ ./node_modules/cozy-ui/react/I18n/translation.jsx
 @ ./node_modules/cozy-ui/react/I18n/index.jsx
 @ ./src/targets/browser/index.jsx
 @ multi webpack-dev-server/client?http://localhost:8888/ webpack/hot/dev-server ./node_modules/@babel/polyfill/lib/index.js ./node_modules/cozy-scripts/utils/reactExposer.js ./src/targets/browser/index.jsx

ERROR in ./node_modules/string.prototype.trim/implementation.js
Module not found: Error: Can't resolve 'es-abstract/2020/ToString' in '/app/mycozyapp/node_modules/string.prototype.trim'
 @ ./node_modules/string.prototype.trim/implementation.js 4:15-51
 @ ./node_modules/string.prototype.trim/index.js
 @ ./node_modules/node-polyglot/index.js
 @ ./node_modules/cozy-ui/react/I18n/translation.jsx
 @ ./node_modules/cozy-ui/react/I18n/index.jsx
 @ ./src/targets/browser/index.jsx
 @ multi webpack-dev-server/client?http://localhost:8888/ webpack/hot/dev-server ./node_modules/@babel/polyfill/lib/index.js ./node_modules/cozy-scripts/utils/reactExposer.js ./src/targets/browser/index.jsx
```

I also tried on a docker environment created with the following script : 
```bash
#!/bin/bash

docker stop cozy-node
docker rm cozy-node
docker run -it --name cozy-node \
    -v $(pwd)/app:/app \
    --entrypoint /bin/sh \
    node:10.22.1-alpine
```

and installing git with the `apk add git` command, to no avail...

**Comment by Crash--** [comment]
Just tested on : 
 Mac OS 10.15.5
 Node 10.21.0
 Yarn 1.16.0 

It works as expected. 

Which version of Yarn do you use?

**Comment by RemiPail** [comment]
Hello,

I work with @nicolaspernoud 
The versions used in the docker environment are :
- Node : 10.22.1
- Yarn : 1.22.4

**Comment by ptbrowne** [comment]
I haven't been able to reproduce either.

I did 

```
cd /tmp
yarn create cozy-app toto
# Responded to everything with defaults
cd toto
yarn start
# the app starts correctly
```

The app starts correctly but its bootstrap code is a bit old so there are some styling issues.

**Comment by ptbrowne** [comment]
J'ai essayé sur un Ubuntu 20 et j'ai reproduit le problème. J'ai du mal à comprendre pourquoi en local sous macOS je me retrouve avec string.prototype.trim en version 1.2.1 et sur ubuntu en version 1.2.2.

Pour régler votre problème et en attendant d'avoir une meilleure solution, vous pouvez faire

```
yarn add string.prototype.trim@1.2.1
```

pour régler le soucis.

**Comment by nicolaspernoud** [comment]
Parfait, merci. Cela va déjà bien nous dépanner.

**Comment by ptbrowne** [comment]
Ca a l'air d'être un problème de configuration de notre côté, car on force la résolution des packages ds le node_modules de l'app (voir webpack.config.base.js). En ajoutant "node_modules" à la liste, on a plus l'erreur, même sous Ubuntu.

**Comment by ptbrowne** [comment]
J'ai publié une beta de cozy-scripts qui devrait résoudre le soucis (ca l'a en tout cas résolu chez moi sur Ubuntu 20). Est ce que vous pouvez enlever string.prototype.trim et installer cozy-scripts@beta et me confirmer que c'est ok chez vous ?

**Comment by RemiPail** [comment]
Merci beaucoup, ça fonctionne !!

**Comment by ptbrowne** [comment]
La version 5.1.1 corrige le problème 🎉
