### ISSUE TITLE
404 on "- a running Cozy development environment"

### ISSUE THREAD

**Issue by sizvix** [cozy/create-cozy-app#1404]
In the readme.md , in the part "Requirements" , the link  "- a running Cozy development environment" is broken

**Comment by sizvix** [comment]
I supposed it should be 
https://docs.cozy.io/en/tutorials/app/#install-the-development-environment

**Comment by Crash--** [comment]
thanks @sizvix ;). https://github.com/cozy/create-cozy-app/pull/1405
